apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: reto-4-rds.creaemiskqh1.us-east-1.rds.amazonaws.com
            - name: WORDPRESS_DB_USER
              value: wordpressuser
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
          - name: efs
            mountPath: /mnt/wordpress
      volumes:
      - name: efs
        persistentVolumeClaim:
          claimName: reto-4-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

